---
version: "2"

linters:
    # not sure what the best approach is, but enabling all and disabling
    # annoying ones seems better since new linters get added automatically
    # without me doing anything
    default: all

    disable:
        # pleasing this one is impossible :D a function is complex if it needs
        # to be complex... setting max-complexity too high makes this useless,
        # so might as well just not use it at all
        - cyclop
        # wants errors as package level variables that get wrapped instead of
        # just doing it inline. code spaghetti for 0 gains in my opinion,
        # especially if the errors are used only once...
        - err113
        # styling/formatting with no impact on functionality
        - funcorder
        # complains about function length. breaking up a clean 100 line function
        # into 5 20 line ones (used only once) is not an improvement at all...
        - funlen
        # same as cyclop
        - gocognit
        # same as cyclop
        - gocyclo
        # can't live without todo comments
        - godox
        # same as cyclop
        - maintidx
        # too annoying
        - mnd
        # same as cyclop
        - nestif
        # styling/formatting with no impact on functionality
        - nlreturn
        # styling/formatting with no impact on functionality
        - noinlineerr
        # does too much stuff
        - revive
        # styling/formatting with no impact on functionality
        - varnamelen
        # styling/formatting with no impact on functionality
        - whitespace
        # styling/formatting with no impact on functionality
        - wsl
        # styling/formatting with no impact on functionality
        - wsl_v5

run:
    # ignore test files
    tests: false
